import React from 'react'
export const array = [
  {
    id: 1,
    name: "Can I try before I subscribe?",
    parag:
      "As a free user you have a limited access to all our tools. By upgrading to Premium, you get access to the same tools with the highest task and size limits.",
    isCompleted: false,
  },
  {
    id: 2,
    name: "I want to purchase multiple user accounts. Can I get a discount?",
    parag: `iLovePDF is already priced to be very affordable. Up to 10 users, there is only Annual membership discount, 33% off. For larger volume of user accounts, please email us.`,
    isCompleted: false,
  },
  {
    id: 3,
    name: "Is there any discount available?",
    parag:
      "Yes. We offer special discounts to students. Just sign up with your student e-mail address and you will automatically qualify for the discount. If your student e-mail address is not recognized, please contact our support team.",
    isCompleted: false,
  },
  {
    id: 4,
    name: "Can I share single billing for multiple accounts?",
    parag: `Yes. You can put everyone's account on one credit card for centralized billing. Just enter the email addresses of your team members and your plan will automatically upgrade.`,
    isCompleted: false,
  },
  {
    id: 5,
    name: "What payment methods do you accept?",
    parag: `We accept payments through Visa, MasterCard, Discover, American Express and others. If you don't want to use a credit card, we accept PayPal among others. If you need to use any other payment method, let us know.`,
    isCompleted: false,
  },
  {
    id: 6,
    name: "Can I cancel my subscription?",
    parag: `Absolutely! If your account doesn’t fit your needs, you can cancel your subscription at any time.`,
    isCompleted: false,
  },
  {
    id: 7,
    name: "What if I need to change my plan partway through my contract?",
    parag: `You can add and remove licenses as needed from your Account. In the same way, you can upgrade your subscription and we'll automatically adjust the pricing.`,
    isCompleted: false,
  },
  {
    id: 8,
    name: "Can you invoice me?",
    parag: `Yes, Tax Invoicing is available for all the Plans. All prices are VAT included. We offer monthly and annual billing. You can manage your Invoices and edit your billing settings from your Account page.`,
    isCompleted: false,
  },
];
export const includedTools = [
  {name: "Merge PDF",sign: <i class='bx bx-check'></i>},
  {name: "Split PDF", sign: <i class='bx bx-check'></i>,},
  { name: "Compress PDF", sign: <i class='bx bx-check'></i> },
  { name: "Office to PDF", sign: <i class='bx bx-check'></i> },
  { name: "WORD to PDF", sign: <i class='bx bx-check'></i> },
  { name: "POWERPOINT to PDF", sign: <i class='bx bx-check'></i> },
  { name: "EXCEL to PDF", sign: <i class='bx bx-check'></i> },
  { name: "PDF to WORD", sign: <i class='bx bx-check'></i> },
  { name: "PDF to WORD (OCR)", sign: <i class='bx bx-x'></i> },
  { name: "PDF to POWERPOINT", sign: <i class='bx bx-check'></i> },
  { name: "PDF to EXCEL", sign: <i class='bx bx-check'></i> },
  { name: "PDF to JPG", sign: <i class='bx bx-check'></i> },
  { name: "Image to PDF", sign: <i class='bx bx-check'></i> },
  { name: "Add page numbers", sign: <i class='bx bx-check'></i> },
  { name: "Add watermark", sign: <i class='bx bx-check'></i> },
  { name: "Rotate PDF", sign: <i class='bx bx-check'></i> },
  { name: "Unlock PDF", sign: <i class='bx bx-check'></i> },
  { name: "Protect PDF", sign: <i class='bx bx-check'></i> },
  { name: "Remove PDF pages", sign: <i class='bx bx-check'></i> },
  { name: "Reorder PDF pages", sign: <i class='bx bx-check'></i> },
  { name: "Organize PDF pages", sign: <i class='bx bx-check'></i> },
  { name: "PDF to PDF/A", sign: <i class='bx bx-x'></i> },
  { name: "Repair PDF", sign: <i class='bx bx-check'></i> },
  { name: "Web to PDF", sign: <i class='bx bx-check'></i> },
  { name: "Edit PDF", sign: <i class='bx bx-check'></i> },
  { name: "PDF Signature", sign: <i class='bx bx-check'></i> },
  { name: "Certify PDF", sign: <i class='bx bx-check'></i> },
  { name: "Scan to PDF", sign: <i class='bx bx-check'></i> },
];
export const allTools = [
  {name: "Merge PDF",sign: <i class='bx bx-check'></i>},
  {name: "Split PDF", sign: <i class='bx bx-check'></i>,},
  { name: "Compress PDF", sign: <i class='bx bx-check'></i> },
  { name: "Office to PDF", sign: <i class='bx bx-check'></i> },
  { name: "WORD to PDF", sign: <i class='bx bx-check'></i> },
  { name: "POWERPOINT to PDF", sign: <i class='bx bx-check'></i> },
  { name: "EXCEL to PDF", sign: <i class='bx bx-check'></i> },
  { name: "PDF to WORD", sign: <i class='bx bx-check'></i> },
  { name: "PDF to WORD (OCR)", sign: <i class='bx bx-check'></i> },
  { name: "PDF to POWERPOINT", sign: <i class='bx bx-check'></i> },
  { name: "PDF to EXCEL", sign: <i class='bx bx-check'></i> },
  { name: "PDF to JPG", sign: <i class='bx bx-check'></i> },
  { name: "Image to PDF", sign: <i class='bx bx-check'></i> },
  { name: "Add page numbers", sign: <i class='bx bx-check'></i> },
  { name: "Add watermark", sign: <i class='bx bx-check'></i> },
  { name: "Rotate PDF", sign: <i class='bx bx-check'></i> },
  { name: "Unlock PDF", sign: <i class='bx bx-check'></i> },
  { name: "Protect PDF", sign: <i class='bx bx-check'></i> },
  { name: "Remove PDF pages", sign: <i class='bx bx-check'></i> },
  { name: "Reorder PDF pages", sign: <i class='bx bx-check'></i> },
  { name: "Organize PDF pages", sign: <i class='bx bx-check'></i> },
  { name: "PDF to PDF/A", sign: <i class='bx bx-check'></i> },
  { name: "Repair PDF", sign: <i class='bx bx-check'></i> },
  { name: "Web to PDF", sign: <i class='bx bx-check'></i> },
  { name: "Edit PDF", sign: <i class='bx bx-check'></i> },
  { name: "PDF Signature", sign: <i class='bx bx-check'></i> },
  { name: "Certify PDF", sign: <i class='bx bx-check'></i> },
  { name: "Scan to PDF", sign: <i class='bx bx-check'></i> },
];
export const limit = [
  {name: "Merge PDF", num:25},
  {name: "Split PDF", num:1},
  { name: "Compress PDF", num:2},
  { name: "Office to PDF", num:1},
  { name: "WORD to PDF", num:1},
  { name: "POWERPOINT to PDF", num:1},
  { name: "EXCEL to PDF", num:1},
  { name: "PDF to WORD", num:1},
  { name: "PDF to WORD (OCR)", num:1},
  { name: "PDF to POWERPOINT", num:1},
  { name: "PDF to EXCEL", num:1},
  { name: "PDF to JPG", num:2},
  { name: "Image to PDF", num:20},
  { name: "Add page numbers", num:2},
  { name: "Add watermark", num:2},
  { name: "Rotate PDF", num:20},
  { name: "Unlock PDF", num:2},
  { name: "Protect PDF", num:2},
  { name: "Organize PDF pages", num:5},
  { name: "PDF to PDF/A", num:1},
  { name: "Repair PDF", num:1},
  { name: "Edit PDF", num:1},
  { name: "PDF Signature", num:3}
]
export const unlimited = [
  {name: "Merge PDF", num:500},
  {name: "Split PDF", num:1},
  { name: "Compress PDF", num:10},
  { name: "Office to PDF", num:10},
  { name: "WORD to PDF", num:10},
  { name: "POWERPOINT to PDF", num:10},
  { name: "EXCEL to PDF", num:10},
  { name: "PDF to WORD", num:10},
  { name: "PDF to WORD (OCR)", num:10},
  { name: "PDF to POWERPOINT", num:10},
  { name: "PDF to EXCEL", num:10},
  { name: "PDF to JPG", num:10},
  { name: "Image to PDF", num:80},
  { name: "Add page numbers", num:10},
  { name: "Add watermark", num:10},
  { name: "Rotate PDF", num:80},
  { name: "Unlock PDF", num:10},
  { name: "Protect PDF", num:80},
  { name: "Organize PDF pages", num:20},
  { name: "PDF to PDF/A", num:10},
  { name: "Repair PDF", num:10},
  { name: "Edit PDF", num:1},
  { name: "PDF Signature", num:5  }
]
export const limitOne = [
  {name: "Merge PDF", num:'100MB'},
  {name: "Split PDF", num:'100MB'},
  { name: "Compress PDF", num:'15MB'},
  { name: "Office to PDF", num:'15MB'},
  { name: "WORD to PDF", num:'15MB'},
  { name: "POWERPOINT to PDF", num:'15MB'},
  { name: "EXCEL to PDF", num:'15MB'},
  { name: "PDF to WORD", num:'15MB'},
  { name: "PDF to WORD (OCR)", num:'15MB'},
  { name: "PDF to POWERPOINT", num:'15MB'},
  { name: "PDF to EXCEL", num:'15MB'},
  { name: "PDF to JPG", num:'25MB'},
  { name: "Image to PDF", num:'40MB'},
  { name: "Add page numbers", num:'100mb'},
  { name: "Add watermark", num:'100mb'},
  { name: "Rotate PDF", num:'100mb'},
  { name: "Unlock PDF", num:'100mb'},
  { name: "Protect PDF", num:'100mb'},
  { name: "Organize PDF pages", num:'100mb'},
  { name: "PDF to PDF/A", num:'100mb'},
  { name: "Repair PDF", num:'100mb'},
  { name: "Edit PDF", num:'100mb'},
  { name: "PDF Signature", num:"50MB"}  
]
export const unlimitedOne = [
  {name: "Merge PDF", num:'4GB'},
  {name: "Split PDF", num:'4GB'},
  { name: "Compress PDF", num:'4GB'},
  { name: "Office to PDF", num:'4GB'},
  { name: "WORD to PDF", num:'4GB'},
  { name: "POWERPOINT to PDF", num:'4GB'},
  { name: "EXCEL to PDF", num:'4GB'},
  { name: "PDF to WORD", num:'4GB'},
  { name: "PDF to WORD (OCR)", num:'4GB'},
  { name: "PDF to POWERPOINT", num:'4GB'},
  { name: "PDF to EXCEL", num:'4GB'},
  { name: "PDF to JPG", num:'4GB'},
  { name: "Image to PDF", num:'4GB'},
  { name: "Add page numbers", num:'4G'},
  { name: "Add watermark", num:'4GB'},
  { name: "Rotate PDF", num:'4GB'},
  { name: "Unlock PDF", num:'4GB'},
  { name: "Protect PDF", num:'4GB'},
  { name: "Organize PDF pages", num:'4GB'},
  { name: "PDF to PDF/A", num:'4GB'},
  { name: "Repair PDF", num:'4GB'},
  { name: "Edit PDF", num:'100mb'},
  { name: "PDF Signature", num:"50MB"} 
]